firestore_snappy.patch.txt: hack test to see if the windows python error can be fixed by using a temporary directory.
A previous commit, bc4a6576f2e6df352d8577c03ab63ba8c1aca981, patched firebase-ios-sdk with https://github.com/firebase/firebase-ios-sdk/pull/9662, which modified cmake builds to create a python virtualenv for each python script.

This, however, ran into a strange problem in the Windows GitHub Actions runners, where creating the virtualenv failed when it attempted to call ensurepip.

The suspected root cause is a MAX_PATH length violation.

To test out this hypothesis, this commit modifies the FirebaseSetupPythonInterpreter() to create the Python virtualenv in a temporary directory instead of a well-defined subdirectory of cmake's binary directory.

This should have a shorter path length for the virtualenv. If this works, then possibly we will need to provide a way to override the base directory for the pyvenv's.

Here is the actual failure from https://github.com/firebase/firebase-cpp-sdk/runs/6083486670

```
-- Found PythonInterp: C:/ProgramData/chocolatey/bin/python2.7.exe (found suitable version "2.7.9", minimum required is "2.7")
-- Found Python3: C:/hostedtoolcache/windows/Python/3.10.4/x64/python3.exe (found version "3.10.4") found components: Interpreter
-- FirebaseSetupPythonInterpreter(FirestoreProtos): Creating Python virtualenv in D:/a/firebase-cpp-sdk/firebase-cpp-sdk/ta/admob/it/bin/external/src/firestore-build/Firestore/Protos/pyvenv/FirestoreProtos using C:/hostedtoolcache/windows/Python/3.10.4/x64/python3.exe
Error: Command '['D:\\a\\firebase-cpp-sdk\\firebase-cpp-sdk\\ta\\admob\\it\\bin\\external\\src\\firestore-build\\Firestore\\Protos\\pyvenv\\FirestoreProtos\\Scripts\\python3.exe', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 3221225781.
CMake Error at bin/external/src/firestore/cmake/python_setup.cmake:133 (message):
  Failed to create a Python virtualenv in
  D:/a/firebase-cpp-sdk/firebase-cpp-sdk/ta/admob/it/bin/external/src/firestore-build/Firestore/Protos/pyvenv/FirestoreProtos
  using C:/hostedtoolcache/windows/Python/3.10.4/x64/python3.exe
Call Stack (most recent call first):
  bin/external/src/firestore/Firestore/Protos/CMakeLists.txt:16 (FirebaseSetupPythonInterpreter)
```