Revert "lambda_event_listener.h: change path to firestore_errors.h include to see if it fixes build errors in CI: lambda_event_listener.h:23:10: fatal error: 'firebase/firestore/firestore_errors.h' file not found"
This change didn't fix anything.

This reverts commit 7343ab51f7f4fba9f6ad5de5299e9a1407cf1679.