Update to Firebase iOS SDK 9.0.0 with necessary changes for Swift support and Firestore (#915)
* Remove the patch to enable Snappy support

* firestore_patch.py: also copy the URL_HASH

* query_main.h: fix build error due to Filter being renamed to FieldFilter.

* user_data_converter_main.cc: fix build error when calling NullValue(), which now just returns a google_firestore_v1_Value instead of a Message<google_firestore_v1_Value>

* Merge in https://github.com/firebase/firebase-cpp-sdk/pull/896 (leveldb_snappy_test.cc: run the test on iOS as well, and other improvements)

* leveldb_snappy_test.cc: re-use the test from the iOS SDK instead of re-writing it.

* leveldb_snappy_test.cc: add a newline at the end of the file.

* query_main.h: add missing #include "Firestore/core/src/core/field_filter.h"

* Set the FIRESTORE_INCLUDE_OBJC cmake cache var to NO to avoid building Objective-C parts of the iOS SDK

This fixes the following build error:

```
FIRFirestore.h:147:20: error: unknown attribute 'swift_async' ignored [-Werror,-Wunknown-attributes]
    __attribute__((swift_async(none)));  // Disable async import due to #9426.
                   ^
1 error generated.
```

which was introduced by https://github.com/firebase/firebase-ios-sdk/pull/9502

* external/pip_requirements.txt: add six

This is an attempt to fix the following build error:

```
Traceback (most recent call last):
  File "Firestore/Protos/tmphmjWeu.py", line 25, in <module>
    import nanopb_generator as nanopb
  File "nanopb/generator/nanopb_generator.py", line 25, in <module>
    import google.protobuf.text_format as text_format
  File "protobuf/python/google/protobuf/text_format.py", line 51, in <module>
    import six
ImportError: No module named six
```

e.g. https://github.com/firebase/firebase-cpp-sdk/runs/6034310890

* Improve FIREBASE_PYTHON_EXECUTABLE cmake cache var and make its usage ubiquitous

* firestore.cmake: bump pinned commit

* Revert "external/pip_requirements.txt: add six" since it didn't fix the problem.

This reverts commit 56553d996678430e756fa2eed6b469aaa8baf299.

* firestore.cmake: fix pinned commit

* Revert "Improve FIREBASE_PYTHON_EXECUTABLE cmake cache var and make its usage ubiquitous"

It seemed to cause problems with the build. There is a better way in the iOS SDK anyways.

This reverts commit c6346fd6c2153d3f04fb35b6da5192a2d70938b2.

* firestore.cmake: update pinned commit

* CMakeLists.txt: Set FIRESTORE_INCLUDE_OBJC as a cache variable so it actually works

* query_main.cc: IsBefore(BoundPosition) -> IsInclusive(BoundPosition)

This fixes several test failures due to incorrect handling of startAfter and endBefore resulting from a change in core::Bound from "before" to "inclusive" in https://github.com/firebase/firebase-ios-sdk/pull/9519

Namely, this fixes the following failure:
```
cursor_test.cc:250: Failure
Expected equality of these values:
  std::vector<std::string>({"c", "f", "b", "e"})
    Which is: { "c", "f", "b", "e" }
  QuerySnapshotToIds(snapshot)
    Which is: { "c", "f" }
[  FAILED  ] FirestoreIntegrationTest.TimestampsCanBePassedToQueriesAsLimits
```

e.g. https://github.com/firebase/firebase-cpp-sdk/runs/6044737005

* firestore.cmake: update pinned commit

* Use staging repo and update to 9.0 podfiles.

Add Swift headers from 9.0.0 zip release.

* Remove streaming support, as it fails with the new Swift SDK.

* Enable Firestore and Admob.

* Remove AdMob for now - it's broken in 7.69.0-cppsdk.

* Don't process swift headers if already processed

* fix nightly version tag

* Fix update dependencies script

* Support directories with spaces

* Exclude swift headers from linter.

* Fix whitespace

* Fix comma

* Fix whitespace.

* Fix Firestore external file.

* Restore new external file and fix include path.

* Fix include files and paths to be compatible with C++ build.

* Format code.

* Add NOLINT

* Remove included test with bad include path.

* Fix internal test podfile

* Fix podfiles

* Revert some junk that got pulled in when #898 was merged into this branch

* Temporarily remove admob from integration_tests.yml too.

* integration_tests.yml: remove admob from another place, since it still seems to be being built

* Revert "integration_tests.yml: remove admob from another place, since it still seems to be being built"

This reverts commit fc6b8458965ee0f6849da344c0ae01823ea599f6.

* Revert "Temporarily remove admob from integration_tests.yml too."

This reverts commit 32aec7e494537766c92fda751cc7ccc59c8618b4.

* Add AdMob back in and refer to new version in staging.

* Speed up update-dependencies zip distribution usage

* Fix substitution.

* Fix header formatting

* Fix spacing.

* Update Xcode version to 12.5.1 and add tests to 13.2.1

* Add new version to readme

* Change Functions iOS SDK and tvOS SDK version to 12.4 (minimum for Swift).

* Since FIRStorageMetadata no longer implements NSCopying, copy it a different way.

* Change deployment version to 12.4 for Storage, required for Swift support.

* Update analytics headers from 9.0.0 Analytics RC.

* Add note about removal of deprecated analytics constants.

* Set analytics deployment target

* Set deployment targets

* Add empty Swift file to sample framework.

* Switch Podfile postprocessing to use python3

* Add empty Swift file to integration test project.

* Add empty Swift file to analytics project

* Add empty.swift to remaining integration test projects.

* Check to make sure that the controller can pause/resume/etc.

* Workaround for pause/cancel/resume semantics changing in 9.x.

* Switch from nightly to release tag for Firestore external dep.

* Update Xcode version to 13.2.1, required version for iOS SDK.

* Change deployment target back to 10.x.

* Fix iOS deployment version back to 10.0

* Add notes about including a swift file

* Change comparison to lower-case to prevent restore_secrets overriding it.

* Clean up the verbose log of file size

* firestore_snappy.patch.txt: remove the patching for https://github.com/firebase/firebase-ios-sdk/pull/9662 (Create individual Python virtualenv's in cmake builds) since it's incorporated into the CocoaPods-9.0.0.nightly tag

* CHERRY PICK from main branch: leveldb_snappy_test.cc: run the test on iOS as well, and other improvements (#896)

This change improves the leveldb_snappy_test.cc to provide stronger guarantees of expected behavior.

* Set block storage for task variable.

* Fix server key.

* Format code.

* test iOS simulator devices

* Windows compatibility for strcasecmp

* test iOS simulator devices

* Update Swift header to include copy method; revert Storage to use it.

* upload ios projects artifacts

* Temporarily disable a test that fails on device when built from cmdline.

* Update the testing Xcode version to 13.3.1

* Change xcode version to 13.3.1 and macos runners to macos-12.

* Restore simulator versions back to previous values

* Reworded some release notes.

(Also replaced a couple tabs with spaces.)

* Revert "upload ios projects artifacts"

This reverts commit e04d6a6de4ba635437dd41bdf97e065eace07024.

* Fix Swift header script to work with multiple URLs.

* Update Swift headers for final 9.0.0 release

* Add readme about ios_pod directory and its swift_headers subdirectory

* Remove staging repo from podfiles. (#923)

* If the zip file can't be downloaded, just skip that step.

Co-authored-by: Denver Coneybeare <dconeybe@google.com>
Co-authored-by: Mou <sunmou@google.com>
Co-authored-by: Mou Sun <69009538+sunmou99@users.noreply.github.com>
Co-authored-by: a-maurice <amaurice@google.com>