Improve `Variant` error message when used with an unsupported type.
In the previous implementation, `set_value_t` was declared to be a template function but never defined (instead, a few specializations were defined). This could cause a linker error when a `Variant` is used with an unsupported type (using `firestore::FieldValue` as the example):
```
ld.lld: error: blaze-out/k8-fastbuild/bin/_solib_k8/libfirebase_Sfirestore_Sclient_Scpp_Slibfield_Uvalue_Utest.ifso: undefined reference to void firebase::Variant::set_value_t<firebase::firestore::FieldValue>(firebase::firestore::FieldValue) [--no-allow-shlib-undefined]
```
(see https://sponge.corp.google.com/invocation?id=0dbf93d2-8644-4058-9b98-0513ad032e08&searchFor=user%3Avarconst)

Deleting the regular template has the advantage of turning it into a compile-time error that contains a reference to the line in the source code that triggers it:

```
In file included from firebase/firestore/client/cpp/src/tests/field_value_test.cc:17:
./firebase/app/client/cpp/src/include/firebase/variant.h:134:5: error: call to deleted member function 'set_value_t'
    set_value_t(value);
    ^~~~~~~~~~~
firebase/firestore/client/cpp/src/tests/field_value_test.cc:295:10: note: in instantiation of function template specialization 'firebase::Variant::Variant<firebase::firestore::FieldValue>' requested here
  return FieldValue{};
         ^
./firebase/app/client/cpp/src/include/firebase/variant.h:1114:8: note: candidate function [with T = firebase::firestore::FieldValue] has been explicitly deleted
  void set_value_t(T value) = delete;
       ^
1 error generated.
```
(see https://sponge.corp.google.com/invocation?id=8122d244-50d5-4072-98fb-9c5c11dc42ad&searchFor=user%3Avarconst)

This should be a non-breaking change (the code that was compiling previously should be unaffected).

PiperOrigin-RevId: 324927992