Set the FIRESTORE_INCLUDE_OBJC cmake cache var to NO to avoid building Objective-C parts of the iOS SDK.
This won't have any effects until the iOS dependencies are updated to a version that includes https://github.com/firebase/firebase-ios-sdk/pull/9658.

This will fix the following build error:

```
FIRFirestore.h:147:20: error: unknown attribute 'swift_async' ignored [-Werror,-Wunknown-attributes]
    __attribute__((swift_async(none)));  // Disable async import due to #9426.
                   ^
1 error generated.
```

which was introduced by https://github.com/firebase/firebase-ios-sdk/pull/9502.

It avoids it by simply not building the file at all :)