Automated g4 rollback of changelist 267398802.
*** Reason for rollback ***

Fails to compile on gLinux via cmake.

Can test a fix via:
mkdir /tmp/firebase_cpp_copybara-internal
git init --bare /tmp/firebase_cpp_copybara-internal
/google/data/ro/teams/copybara/copybara third_party/firebase/cpp/copy.bara.sky piper_to_git_internal --force --ignore-noop
git clone /tmp/firebase_cpp_copybara-internal ~/firebase_cpp
mkdir ~/firebase_cpp/build
cd ~/firebase_cpp/build
cmake ..
make

Error im seeing is:

In file included from /usr/include/c++/8/algorithm:62,
                 from ~/firebase_cpp/app/src/reference_counted_future_impl.cc:19:
/usr/include/c++/8/bits/stl_algo.h: In instantiation of ‘_IIter std::find_if(_IIter, _IIter, _Predicate) [with _IIter = firebase::intrusive_list<firebase::{anonymous}::CompletionCallbackData>::intrusive_list_iterator<false>; _Predicate = const firebase::CompletionMatcher&]’:
~/firebase_cpp/app/src/reference_counted_future_impl.cc:573:32:   required from here
/usr/include/c++/8/bits/stl_algo.h:3931:37: error: use of deleted function ‘firebase::CompletionMatcher::CompletionMatcher(const firebase::CompletionMatcher&)’
        __gnu_cxx::__ops::__pred_iter(__pred));

*** Original change description ***

Automated g4 rollback of changelist 267236680.

*** Reason for rollback ***

Roll-forward (i.e. rollback of rollback) after fixing the breakage that caused the initial rollback.  This CL has three fixes:
(1) It incorporates the fixes by varconst@ in CL 267229592, which fixed a problem where
    some of the references to std::function were not inside
    "#if defined(FIREBASE_USE_STD_FUNCTION)".
(2) It deletes an unnecessary (and wrong) friend declaration that was causing an ambiguity error; ther...

***

PiperOrigin-RevId: 268010105