query_main.h: fix build error due to Filter being renamed to FieldFilter.
This fixes the following build error in `ubuntu-latest-Release-x64-static`:

```
firestore/src/main/query_main.h:185:34: error: no type named 'Operator' in 'firebase::firestore::core::Filter'
  using Operator = core::Filter::Operator;
                   ~~~~~~~~~~~~~~^
```

e.g. https://github.com/firebase/firebase-cpp-sdk/runs/6065960625